"""The pre-upload format gate, exercised as JavaScript.

A whole genome is a multi-hour upload. Refusing it afterwards, when the format
was never readable, wastes all of that — so the gate runs before a byte is sent.
That makes a FALSE REFUSAL the expensive failure: it turns a working upload into
an impossible one, with no way for the user to argue. The cases that must be
ACCEPTED therefore matter more here than the ones that must be refused, and the
zip case matters most of all — 23andMe, AncestryDNA, MyHeritage and FTDNA all
hand the user a .zip.

Run in node against the real served page, so what is tested is what ships.
"""
import json
import re
import shutil
import subprocess

import pytest

from dnareport.landing import LANDING_HTML

pytestmark = pytest.mark.skipif(shutil.which("node") is None,
                                reason="node not available to evaluate page JS")


def _page_js() -> str:
    return "\n".join(re.findall(r"<script>(.*?)</script>", LANDING_HTML, re.S))


def _harness(cases) -> list:
    """Evaluate extAllowed()/classifyHead() from the served page against cases."""
    js = _page_js()
    # the page's script is an IIFE wired to DOM nodes; lift out just the two pure
    # functions plus the constant they close over, so no DOM stub is needed
    wanted = []
    for name in ("ALLOWED_EXT", "SNIFF_BINARY", "SNIFF_VCF"):
        m = re.search(rf"\bconst {name}\s*=.*?;", js, re.S)
        assert m, f"{name} missing from the served page"
        wanted.append(m.group(0))
    for fn in ("extAllowed", "classifyHead"):
        m = re.search(rf"\bfunction {fn}\(.*?\n \}}", js, re.S)
        assert m, f"{fn}() missing from the served page"
        wanted.append(m.group(0))
    prog = "\n".join(wanted) + f"""
const cases = {json.dumps(cases)};
console.log(JSON.stringify(cases.map(c =>
  ({{allowed: extAllowed(c.name), label: classifyHead(c.name, c.text)}}))));
"""
    out = subprocess.run(["node", "-e", prog], capture_output=True, text=True,
                         timeout=60)
    assert out.returncode == 0, out.stderr
    return json.loads(out.stdout)


_23ANDME = ("# This data file generated by 23andMe at: Mon Jan 1 00:00:00 2023\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs4477212\t1\t82154\tAA\nrs3094315\t1\t752566\tAG\n")
_VCF = "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\n13\t32316419\t.\tCAG\tC\n"
_BETA = "probe,S1\ncg00000029,0.55\ncg00000109,0.72\n"
_BEDMETHYL = "chr1\t10468\t10469\tm,CG,0\t3\t+\t10468\t10469\t255,0,0\t3\t100.0\n"


def test_the_common_consumer_zip_is_never_refused():
    # the single most important case: the container is compressed, so its head
    # sniffs as noise; judging it on that would break most real uploads
    r = _harness([{"name": "23andMe_export.zip", "text": "PK\x03\x04\x00\x00garbage"}])[0]
    assert r["allowed"] is True
    assert r["label"] is not None


@pytest.mark.parametrize("name,text", [
    ("genome_Jane_Doe_v5_Full_20230101.txt", _23ANDME),
    ("genome.vcf", _VCF),
    ("genome.vcf.gz", ""),                       # binary; judged by extension
    ("betas.csv", _BETA),
    ("calls.bedmethyl", _BEDMETHYL),
    ("array.idat", ""),
    ("ont.bam", ""),
    ("AncestryDNA.txt", "#AncestryDNA raw data download\nrsid\tchr\tpos\tallele1\n"),
])
def test_real_formats_are_accepted(name, text):
    r = _harness([{"name": name, "text": text}])[0]
    assert r["allowed"] is True, f"{name} refused at the extension gate"
    assert r["label"] is not None, f"{name} refused by the content sniff"


def test_a_23andme_shaped_tsv_is_accepted_despite_its_extension():
    # extension alone must not decide: .tsv carries several formats, and this one
    # is a genotype export the server can read
    body = "rs4477212\t1\t82154\tAA\nrs3094315\t1\t752566\tAG\n"
    r = _harness([{"name": "mygenome.tsv", "text": body}])[0]
    assert r["allowed"] is True
    assert r["label"] is not None


def test_an_unreadable_tsv_is_refused_by_content_not_extension():
    # Colby's 1.4 GB case: allowed extension, but no format we parse. It must be
    # caught here rather than after the upload.
    body = ("sample\tchrom\tstart\tend\tref\talt\tqual\tdepth\tvaf\tgene\tnote\tx\ty\n"
            "S1\t1\t100\t200\tA\tT\t99\t30\t0.5\tBRCA2\t-\t-\t-\n")
    r = _harness([{"name": "wgs_variants.tsv", "text": body}])[0]
    assert r["allowed"] is True          # extension is plausible
    assert r["label"] is None            # content is not


@pytest.mark.parametrize("name", [
    "genome.vcf.bz2",     # bz2 is not supported anywhere in this product
    "results.pdf",
    "notes.docx",
    "photo.jpg",
    "archive.7z",
])
def test_formats_with_no_parser_are_refused_without_reading(name):
    r = _harness([{"name": name, "text": ""}])[0]
    assert r["allowed"] is False, f"{name} should not reach the content sniff"
